### ISSUE TITLE
Cannot read property 'beforeCompile' of undefined 

### ISSUE THREAD

**Issue by Craig-Cheng** [liximomo/lazy-compile-webpack-plugin#2]
### Version:
 "webpack": "^3.6.0",
  node: v8.11.1

### Problem: 
 it can't run when using this plugin

### Reason:
TypeError: Cannot read property 'beforeCompile' of undefined
    at LazyCompilePlugin.apply (D:\lunkr-project\hxphone-main-stable\node_modules\lazy-compile-webpack-plugin\lib\plugin.js:57:20)
    at Compiler.apply (D:\lunkr-project\hxphone-main-stable\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (D:\lunkr-project\hxphone-main-stable\node_modules\webpack\lib\webpack.js:33:19)
    at startDevServer (D:\lunkr-project\hxphone-main-stable\node_modules\webpack-dev-server\bin\webpack-dev-server.js:367:16)
    at processOptions (D:\lunkr-project\hxphone-main-stable\node_modules\webpack-dev-server\bin\webpack-dev-server.js:350:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by liximomo** [comment]
Only support webpack 4.0.0 above.
